image: node:10.15.1

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install
    - cp config-example.js config.js
  artifacts:
    paths:
      - node_modules/

test_with_lab:
  stage: test
  script: npm test
